export type Language = "en" | "hi";
export type PaymentMode = "cash" | "upi" | "bank_transfer" | "other";

export interface Customer {
  id: string;
  customerCode?: string; // e.g. CUST001 - auto-generated by the repository on create
  name: string;
  phone: string;
  address?: string;
  preferredLanguage: Language;
  notes?: string;
  status: "active" | "archived";
  createdAt: string;
  updatedAt: string;
}

export interface Payment {
  id: string;
  customerId: string;
  loanId: string;
  installmentNo?: number;
  amount: number;
  paymentDate: string;
  paymentMode: PaymentMode;
  notes?: string;
  createdAt: string;
}

export interface FineAdjustment {
  id: string;
  loanId: string;
  installmentNo: number;
  originalFine: number;
  waivedAmount: number;
  reason?: string;
  createdAt: string;
  createdBy?: string;
}

export interface AppNotification {
  id: string;
  type: "upcoming" | "due_today" | "overdue" | "fine_applied" | "payment_received" | "fine_waived";
  customerId?: string;
  loanId?: string;
  title: string;
  message: string;
  read: boolean;
  createdAt: string;
}

export interface FinancerSettings {
  name: string;
  businessName: string;
  mobile: string;
  whatsappNumber: string;
  email: string;
  address: string;
  language: Language;
  currency: string;
  dateFormat: string;
  whatsappDefaultMessageHi: string;
  whatsappDefaultMessageEn: string;
  notifications: {
    push: boolean;
    dueDateReminders: boolean;
    overdueAlerts: boolean;
    weeklySummary: boolean;
  };
}

export interface AuditLogEntry {
  id: string;
  entity: string;
  entityId: string;
  action: string;
  details: string;
  performedAt: string;
}
